default: &default
  timeout: 5000
  adapter: postgresql
  encoding: utf8
  database: idealhat_dev
  pool: 5

development:
  <<: *default

test:
  <<: *default
  database: idealhat_test

production:
  <<: *default