default: &default
  timeout: 5000
  adapter: postgresql
  encoding: utf8
  database: vector_prime_dev
  pool: 5

development:
  <<: *default

test:
  <<: *default
  database: vector_prime_test

production:
  <<: *default